CREATE TABLE QB (
    ID int NOT NULL AUTO_INCREMENT,
    PLAYER varchar(22) NOT NULL,
    TEAM varchar(3) NOT NULL,
    TD smallint NOT NULL,
    YDSPERGAME smallint NOT NULL,
    PRIMARY KEY (ID)
);
ALTER TABLE QB AUTO_INCREMENT=1;
CREATE TABLE RB (
    ID int NOT NULL AUTO_INCREMENT,
    PLAYER varchar(22) NOT NULL,
    TEAM varchar(3) NOT NULL,
    TD smallint NOT NULL,
    YDSPERGAME smallint NOT NULL,
    PRIMARY KEY (ID)
);
ALTER TABLE RB AUTO_INCREMENT=1;
CREATE TABLE WR (
    ID int NOT NULL AUTO_INCREMENT,
    PLAYER varchar(22) NOT NULL,
    TEAM varchar(3) NOT NULL,
    TD smallint NOT NULL,
    YDSPERGAME smallint NOT NULL,
    PRIMARY KEY (ID)
);
ALTER TABLE WR AUTO_INCREMENT=1;
/*CREATE TEMPORARY TABLE UPDATEQB (
    ID int NOT NULL AUTO_INCREMENT,
    PLAYER varchar(22) NOT NULL,
    TEAM varchar(3) NOT NULL,
    TD smallint NOT NULL,
    YDSPERGAME smallint NOT NULL,
    PRIMARY KEY (ID)
);


CREATE TEMPORARY TABLE UPDATERB (
    ID int NOT NULL AUTO_INCREMENT,
    PLAYER varchar(22) NOT NULL,
    TEAM varchar(3) NOT NULL,
    TD smallint NOT NULL,
    YDSPERGAME smallint NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TEMPORARY TABLE UPDATE=WR (
    ID int NOT NULL AUTO_INCREMENT,
    PLAYER varchar(22) NOT NULL,
    TEAM varchar(3) NOT NULL,
    TD smallint NOT NULL,
    YDSPERGAME smallint NOT NULL,
    PRIMARY KEY (ID)
);*/